### ISSUE TITLE
Request for another paper "Indoor Panorama Planar 3D Reconstruction via Divide and Conquer"

### ISSUE THREAD

**Issue by zengbw** [sunset1995/HoHoNet#4]
Thank you for release the cool work of HoHoNet.
I found another paper("Indoor Panorama Planar 3D Reconstruction via Divide and Conquer") also from you. Do you have any plan to open source too?
Or will you release the pre-train weight for testing and comparing with relative papers?

**Comment by sunset1995** [comment]
Thanks for interested in our work.
I try my best to release the code by this week.

**Comment by zengbw** [comment]
Thank you. 
Looking forward to updating information.

**Comment by sunset1995** [comment]
Finally.
https://github.com/sunset1995/PanoPlane360

**Comment by zengbw** [comment]
Thanks a lot.
